const items = [
    {
      id: 1,
      userName: "John Doe",
      itemName: "MacBook Pro",
      price: "2500",
      likes: 35,
      noOfComments: 15,
      description: "Discover the MacBook Pro laptop with the M4 family of chips, built for Apple Intelligence. Get credit when you trade in an eligible Mac. Buy now. #Apple #MacBook #M4.",
      avatar: "https://randomuser.me/api/portraits/men/46.jpg",
      image: "https://picsum.photos/id/8/5000/3333",
    },
    {
      id: 2,
      userName: "Jane Foster",
      itemName: "Cannon EOS",
      price: "1020",
      likes: 21,
      noOfComments: 10,
      description: "Packed with sophisticated features like higher-end models and yet easy to use, the #EOS #850D is a reasonably-priced DSLR that delivers the quality you need. Perfect for those serious on picking up photography, this is the simple and affordable choice as your stepping stone towards mastery in photography.",
      avatar: "https://randomuser.me/api/portraits/women/29.jpg",
      image: "https://picsum.photos/id/435/1200/800",
    },
    {
      id: 3,
      userName: "Byrne Wilson",
      itemName: "Kindle Books",
      price: "170",
      likes: 87,
      noOfComments: 22,
      description: "Shop all Kindle books. Kindle Monthly Deals: Up to 80% off top reads. More to Explore. #Arts #Photography #Biographies #Memoirs #Business #Money.",
      avatar: "https://randomuser.me/api/portraits/men/45.jpg",
      image: "https://picsum.photos/id/367/4928/3264",
    },
    {
      id: 4,
      userName: "Lee Anderson",
      itemName: "Samsung Galaxy S24 8GB RAM 256GB",
      price: "841",
      likes: 54,
      noOfComments: 12,
      description: "8GB RAM | 256GB ROM; 6.1 -inch Dynamic LTPO AMOLED 2X screen; 50MP camera for high-resolution stunners; Enhanced low-light selfies; Exynos 240",
      avatar: "https://randomuser.me/api/portraits/women/21.jpg",
      image: "https://picsum.photos/id/373/4896/3264",
    },
    {
      id: 5,
      userName: "Brian Adams",
      itemName: "FG/FS Series",
      price: "975",
      likes: 65,
      noOfComments: 14,
      description: "We offer premium, world-class audio visual, musical instrument products and services to consumers at highly affordable rates.",
      avatar: "https://randomuser.me/api/portraits/men/71.jpg",
      image: "https://picsum.photos/id/145/4288/2848",
    },
  ];
  
  module.exports = items;
  