const items = [
    {
      id: 1,
      userName: "John Doe",
      itemName: "Taylor Swift",
      price: "110",
      likes: 35,
      noOfComments: 15,
      description: "A great product! #trendy #Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      avatar: "https://randomuser.me/api/portraits/men/70.jpg",
      image: "https://picsum.photos/id/64/4326/2884",
    },
    {
      id: 2,
      userName: "Jane Smith",
      itemName: "Taylor Swift",
      price: "520",
      likes: 21,
      noOfComments: 10,
      description: "Another amazing item! #hot #fashion Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
      avatar: "https://randomuser.me/api/portraits/men/71.jpg",
      image: "https://picsum.photos/id/119/3264/2176",
    },
    {
      id: 3,
      userName: "Byrne Wilson",
      itemName: "Taylor Swift",
      price: "170",
      likes: 87,
      noOfComments: 22,
      description: "Another amazing item! #hot #fashion",
      avatar: "https://randomuser.me/api/portraits/men/45.jpg",
      image: "https://picsum.photos/id/119/3264/2176",
    },
    {
      id: 4,
      userName: "Lee Anderson",
      itemName: "Taylor Swift",
      price: "841",
      likes: 54,
      noOfComments: 12,
      description: "Another amazing item! #hot #fashion",
      avatar: "https://randomuser.me/api/portraits/women/21.jpg",
      image: "https://picsum.photos/id/119/3264/2176",
    },
    {
      id: 5,
      userName: "Taylor Swift",
      itemName: "Taylor Swift",
      price: "975",
      likes: 65,
      noOfComments: 14,
      description: "Another amazing item! #hot #fashion",
      avatar: "https://randomuser.me/api/portraits/women/71.jpg",
      image: "https://picsum.photos/id/119/3264/2176",
    },
  ];
  
  module.exports = items;
  